### ISSUE TITLE
Support sending metrics via CloudWatch

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_aws#25]
Inspired by [this `mod_statsd` request](https://github.com/Castaglia/proftpd-mod_statsd/issues/16) from @tspicer, the `mod_aws` module should similarly support sending the same metrics to AWS [CloudWatch](http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/Welcome.html).

**Comment by Castaglia** [comment]
The `mod_statsd` metrics are a counter and timer _per command_, with some other metrics.  Should those same fine-grained metrics be emitted to CloudWatch?  Or would higher-level metrics, such as the following, be more desirable?
* connections (count, timing)
* logins (success/failure/total count)
* directory listings (success/failure/total count, timing)
* file uploads (success/failure/total count, timing)
* file downloads (success/failure/total count, timing)
* timeouts (count)
* TLS protocol version (count)
* TLS cipher (count)

Many of the above higher-level metrics can be created/computed from the per-command metrics...

**Comment by tspicer** [comment]
I think that is a strong candidate list. I'm asking someone on my team to provide some suggestions

**Comment by tspicer** [comment]
Would any of the SQL related events (assuming the use of SQL) fall under those categories?

**Comment by Castaglia** [comment]
Not directly, no -- the above metrics (outside of the TLS ones) are independent of the underlying mechanisms (SQL, LDAP, RADIUS, etc).

What sort of SQL-related metrics would you like to see?

**Comment by tspicer** [comment]
I think we would want to understand connections/errors mostly. We could set some alarms based on thresholds we are seeing being hit and adjust accordingly.

**Comment by Castaglia** [comment]
FYI, while waiting for this work to complete, another approach might be to use the [`mod_statsd`](https://github.com/Castaglia/proftpd-mod_statsd) module, and configure your `statsd` to use AWS CloudWatch as a "backend" using:
* [`aws-cloudwatch-statsd-backend`](https://github.com/camitz/aws-cloudwatch-statsd-backend)
* [`statsd-cloudwatch-backend`](https://github.com/dylanmei/statsd-cloudwatch-backend)

**Comment by Castaglia** [comment]
Initial CloudWatch support has been merged to master.  Please try it out, help shake out bugs, offer feedback!
