### ISSUE TITLE
AWS Health Check didn't listen on port 8080

### ISSUE THREAD

**Issue by nvmker** [Castaglia/proftpd-mod_aws#32]
Hi,
We have a following situation with mod_aws and health check:
We configured ProFTPD to run in EC2 instance as ECS service, in Docker container, added mod_aws with following config:
```
<IfModule mod_aws.c>
  AWSEngine on
  AWSServices CloudWatch
  AWSCredentials Environment IAM Profile Properties
  AWSCloudWatchDimensions Protocol InstanceId AvailabilityZone
  AWSCloudWatchNamespace proftpd
  AWSHealthCheck "/health" 127.0.0.1 8080
  AWSRegion us-east-1
</IfModule>
```
Module is working and sending metrics to CloudWatch, but health check function didn't working, it doesn't listen on port 8080 on localhost or any other IP address if I point it.
I've tried to debug it with -d20 and TraceLog, but didn't see any useful error messages in logs.

**Comment by Castaglia** [comment]
For my testing purposes: how did you notice that the health check listener was not there?  That is, did you not see the expected entry in output from `netstat -nlp`, or did you notice other behavior which indicated a health check issue?

**Comment by nvmker** [comment]
I've noticed that with netstat in the docker container.

**Comment by Castaglia** [comment]
This should now be fixed in master; can you confirm?

**Comment by nvmker** [comment]
Healthchecks now works as expected, thanks!
But there is another issue with mod_aws, SFTP is not working with mod_aws, we are using following configuration ELB with enabled Proxy Protocol>ProFTPD with mod_sftp and mod_proxy_protocol. I've didn't checked it before your changes, so this may be an earlier issue.
I can create a separate issue in github for that and also can do a more tests with our configuration, if you need it.

**Comment by Castaglia** [comment]
Yes, please do file a separate ticket for the mod_aws+mod_sftp issue.  I'll close this ticket as fixed.  Thanks!
