### ISSUE TITLE
SFTP and PROXY protocol not working with mod_aws

### ISSUE THREAD

**Issue by nvmker** [Castaglia/proftpd-mod_aws#34]
Hi,
I have the follwing issue with mod_aws:
SFTP didn't working and client shows me the error about bad packet lenght.
We are using the following configuration:
ELB>EC2 instance with ProFTPD inside the docker container.
When I've tried to disable mod_aws, everything works as expected.
Here is our mod_aws configuration:
```
<IfModule mod_aws.c>
  AWSEngine on
  AWSServices CloudWatch
  AWSCredentials Environment IAM Profile Properties
  AWSCloudWatchDimensions Protocol InstanceId AvailabilityZone
  AWSCloudWatchNamespace proftpd
  AWSHealthCheck "/health" 0.0.0.0 8080
  AWSRegion us-east-1
</IfModule>
```

**Comment by Castaglia** [comment]
Could you provide the full `proftpd.conf`, showing your `mod_sftp` configuration *and* the `mod_aws` configuration, please?

Is the ELB configured with a TCP, or a TLS, listener?  Is it using the PROXY protocol?

**Comment by nvmker** [comment]
I've sent configs to your email directly.
ELB configured with TCP listener with proxy protocol enabled.

**Comment by Castaglia** [comment]
Thanks!  Would you also be able to add the `proftpd -V` output here, please?

**Comment by Castaglia** [comment]
I'm assuming that you're using some sort of YAML interpreter to resolve `{{PROXY_STATUS}}`, in the `proxy.conf` file, to "on"?

Also, would you be able to provide a screenshot of your ELB settings, or something to help me better see the exact ELB listeners/configuration?

**Comment by nvmker** [comment]
Here is proftpd -V output:
```
Compile-time Settings:
  Version: 1.3.7rc1 (git)
  Platform: LINUX [Linux 4.9.32-15.41.amzn1.x86_64 x86_64]
  Built: Thu Oct 26 2017 21:40:56 UTC
  Built With:
    configure  '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libexecdir=/usr/libexec/proftpd' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--localstatedir=/var/run/proftpd' '--disable-auth-pam' '--disable-strip' '--enable-facl' '--disable-ipv6' '--enable-nls' '--enable-openssl' '--enable-ctrls' '--enable-pcre' '--enable-autoshadow' '--enable-tunable-buffer-size' '--enable-sendfile' '--enable-ipv6' '--enable-dso' '--with-libraries=/usr/lib' '--with-includes=/usr/include/mysql' '--with-includes=/usr/include/libxml2' '--with-modules=mod_readme:mod_dynmasq' '--with-shared=mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_sql:mod_sql_passwd:mod_sql_mysql:mod_ban:mod_facl:mod_rewrite:mod_site_misc:mod_ifversion:mod_dnsbl:mod_qos:mod_sftp:mod_sftp_sql:mod_ifsession:mod_quotatab:mod_quotatab_file:mod_quotatab_sql:mod_exec:mod_digest:mod_geoip:mod_statcache:mod_proxy_protocol'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic -L/usr/lib -L/usr/lib
  LIBS: -lintl  -lpcreposix -lpcre -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap -lsupp -lresolv -lresolv -lcrypt

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /var/run/proftpd/proftpd.pid
    Scoreboard File:
      /var/run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    + Autoshadow support
    + Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    + NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by Castaglia** [comment]
Thanks for the screenshots.  I'm now curious about the logs that you might have, from ProFTPD, showing the error.  Specifically,  could you add the following to the top of your ProFTPD configuration, attempt an SFTP connection through the ELB, and attach the generated log?

    TraceLog /path/to/proftpd-trace.log
    Trace aws:20 netio:20 proxy_protocol:20 ssh2:20 sftp:20

I'm hoping these detailed trace logs, particularly the "proxy_protocol" channel, will help provide more information on just what bytes are being sent by the ELB, to ProFTPD.

**Comment by Castaglia** [comment]
Hmm.  I've _also_ seen cases where using:

    SFTPCryptoDevice         all

does not work as expected (_e.g._ can lead to the "bad packet length" errors you mentioned).  Thus an additional experiment is to comment out this directive from your mod_sftp configuration.

**Comment by nvmker** [comment]
I've tried to comment out "SFTPCryptoDevice all", but this is doesn't helps.
I sent trace log to your email.
Thanks!

**Comment by Castaglia** [comment]
OK.  Things are getting murkier now.  I can _sometimes_ reproduce this behavior, using HAproxy 1.5.19.  But sometimes it works.

I _did_ just push some `mod_aws` changes, related to the `AWSHealthCheck` listener, which might have improved things for you; using the latest `mod_aws` would be a good experiment.

**Comment by nvmker** [comment]
It's working now, thank you!

**Comment by Castaglia** [comment]
Excellent news!  I'm very glad it's working for you now.
