### ISSUE TITLE
New AWS Network Load Balancer is unstable with HTTP healthchecks

### ISSUE THREAD

**Issue by nvmker** [Castaglia/proftpd-mod_aws#35]
Hi,
I've tried to configure new NLB balancer with proftpd/mod_aws, but it works unstable with HTTP healthchecks, hosts become unhealthy very fast, and sometimes even not become healthy after initial healthchecks. There is less options to tune-up in NLB healthchecks settings:

HealthCheckTimeoutSeconds is fixed to 6 seconds for HTTP
HealthCheckIntervalSeconds can be 10 or 30 seconds
HealthyThresholdCount and UnhealthyThresholdCount will be the same

I can suggest that this causes much more aggressive healthchecks and mod_aws didn't handle it.
Maybe HTTP keep-alive can solve this issues.

**Comment by Castaglia** [comment]
Are there any log messages in the `AWSLog`, or `TraceLog` for `mod_aws`-related channels, that might help indicate any errors/issues?

Similarly, could you provide the NLB configuration you used, so that I can attempt to reproduce the issue?
