### ISSUE TITLE
Implement timeout for AWS healthcheck requests

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_aws#45]
As noted here, it is possible to "stall" ProFTPD when it is configured to use `mod_aws`' AWSHealthcheck, by connecting to the configured healthcheck address/port using _e.g._ `telnet` or `nc`, and *not* sending the expected HTTP request:
* https://github.com/Castaglia/proftpd-mod_aws/issues/41#issuecomment-1687423081

This happens because `mod_aws` is blocking, waiting to read the HTTP request.

To prevent such situations, the `mod_aws` module should have a ~~configurable~~ timeout for such healthcheck requests, _e.g._ 1-2 secs.

**Comment by Castaglia** [comment]
Fixed in master.

**Comment by 3dw1n** [comment]
Thanks!!!! Will check it out when I'm back from holidays :-)

**Comment by 3dw1n** [comment]
works great, thanks!!!
